In [75]:
import numpy as np

In [2]:
x = np.asarray([1, 0, 2, -1])

In [5]:
ind = np.argsort(x)

In [7]:
y = x[ind]

In [8]:
y[:2]

array([-1,  0])

In [18]:
e = 0.3

In [19]:
i = int(e * x.shape[0])

In [20]:
y[:i]

array([-1])

In [21]:
y[i:]

array([0, 1, 2])

In [25]:
np.sum(y > 0)

2

In [1]:
x = None
i = 0

while x is None:
    print(x, i)
    if i > 10:
        x = i
    else:
        i = i + 1   

None 0
None 1
None 2
None 3
None 4
None 5
None 6
None 7
None 8
None 9
None 10
None 11


In [2]:
x

11

In [15]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, True])

In [16]:
c = [ai ^ bi for (ai, bi) in zip(a, b)]

In [17]:
c

[False, True, True, True]

In [18]:
c

[False, True, True, True]

In [19]:
b[a] = False

In [20]:
b

array([False,  True, False,  True])

In [21]:
mean = [0, 0]
cov = [[1, 0], [0, 100]] 

In [23]:
np.random.multivariate_normal(mean, cov, 16)

array([[ -0.07546955,   1.86821571],
       [ -0.66592994, -10.76080399],
       [  0.64791538,   4.06324303],
       [ -0.64810298,   3.13717033],
       [ -1.12200886,  -9.31832777],
       [ -1.35630834,   3.55074326],
       [  0.12533592, -36.42995577],
       [  1.5907596 ,  -0.63835985],
       [  1.62950486,  -3.0791004 ],
       [ -0.23117823, -15.09675248],
       [  0.03774592,  13.84758932],
       [  2.1045936 ,   6.01099099],
       [  1.21828357,  -8.94053307],
       [  0.24099932,   9.11023687],
       [  2.70798691,  12.8168607 ],
       [  0.04498538, -12.68958055]])

In [64]:
f = np.array([1, 0.5, 7, 0.01])

In [65]:
ind = np.argsort(f)

In [66]:
ind

array([3, 1, 0, 2])

In [67]:
f[ind]

array([0.01, 0.5 , 1.  , 7.  ])

In [53]:
arr = np.array([10, 20, 30, 40, 50])

In [54]:
arr

array([10, 20, 30, 40, 50])

In [60]:
idx = np.array([1, 0, 3, 4, 2])

In [61]:
arr[idx]

array([20, 10, 40, 50, 30])

In [70]:
x = np.array([[17, 2], [18, 3], [10, 6], [1, 9]])

In [71]:
x[ind]

array([[ 1,  9],
       [18,  3],
       [17,  2],
       [10,  6]])

In [76]:
I = np.eye(4)

In [77]:
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
np.random.shuffle(I)

In [86]:
I

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [83]:
y = np.random.rand(8,4)

In [87]:
y

array([[0.41218627, 0.89364451, 0.37046047, 0.80417434],
       [0.01743072, 0.07966169, 0.32912728, 0.88162142],
       [0.5360906 , 0.72553424, 0.97079593, 0.01066801],
       [0.82892015, 0.08918103, 0.32175814, 0.31331461],
       [0.5740572 , 0.41359837, 0.2747143 , 0.16089746],
       [0.50253554, 0.73804187, 0.24916718, 0.83382277],
       [0.99464329, 0.66927975, 0.74348744, 0.80200038],
       [0.53976005, 0.2272858 , 0.73449478, 0.74643519]])

In [89]:
z = np.dot(y, I)

In [90]:
z

array([[0.89364451, 0.37046047, 0.41218627, 0.80417434],
       [0.07966169, 0.32912728, 0.01743072, 0.88162142],
       [0.72553424, 0.97079593, 0.5360906 , 0.01066801],
       [0.08918103, 0.32175814, 0.82892015, 0.31331461],
       [0.41359837, 0.2747143 , 0.5740572 , 0.16089746],
       [0.73804187, 0.24916718, 0.50253554, 0.83382277],
       [0.66927975, 0.74348744, 0.99464329, 0.80200038],
       [0.2272858 , 0.73449478, 0.53976005, 0.74643519]])

In [92]:
np.dot(z, I.T)

array([[0.41218627, 0.89364451, 0.37046047, 0.80417434],
       [0.01743072, 0.07966169, 0.32912728, 0.88162142],
       [0.5360906 , 0.72553424, 0.97079593, 0.01066801],
       [0.82892015, 0.08918103, 0.32175814, 0.31331461],
       [0.5740572 , 0.41359837, 0.2747143 , 0.16089746],
       [0.50253554, 0.73804187, 0.24916718, 0.83382277],
       [0.99464329, 0.66927975, 0.74348744, 0.80200038],
       [0.53976005, 0.2272858 , 0.73449478, 0.74643519]])

In [94]:
x_1, x_2 = np.split(x, 2)

In [95]:
x_1, x_2

(array([[17,  2],
        [18,  3]]), array([[10,  6],
        [ 1,  9]]))

In [96]:
x

array([[17,  2],
       [18,  3],
       [10,  6],
       [ 1,  9]])